/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MenuIndexImport } from './routes/menu/index'
import { Route as MenuGroupGroupIdImport } from './routes/menu/group/$groupId'

// Create Virtual Routes

const OrdersLazyImport = createFileRoute('/orders')()

// Create/Update Routes

const OrdersLazyRoute = OrdersLazyImport.update({
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders.lazy').then((d) => d.Route))

const MenuIndexRoute = MenuIndexImport.update({
  path: '/menu/',
  getParentRoute: () => rootRoute,
} as any)

const MenuGroupGroupIdRoute = MenuGroupGroupIdImport.update({
  path: '/menu/group/$groupId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      preLoaderRoute: typeof OrdersLazyImport
      parentRoute: typeof rootRoute
    }
    '/menu/': {
      preLoaderRoute: typeof MenuIndexImport
      parentRoute: typeof rootRoute
    }
    '/menu/group/$groupId': {
      preLoaderRoute: typeof MenuGroupGroupIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  OrdersLazyRoute,
  MenuIndexRoute,
  MenuGroupGroupIdRoute,
])

/* prettier-ignore-end */
